spring:
  profiles:
   active:
   - dev
---
spring:
  profiles: dev  #开发环境
  application:
   name: gc-test-platform-config-dev
---
spring:
  profiles: test  #测试环境
  application:
   name: gc-test-platform-config-test
---
spring:
  profiles: prod #生产环境
  application:
   name: gc-test-platform-config-prod